### ISSUE TITLE
[Question]: How to use secret management?

### ISSUE THREAD

**Issue by tom-tubeless** [tiredofit/nixos-config#2]
# Question
hey @tiredofit. Great configuration that you crafted there.
I am using NixOS for a while now and your repo convinced me, that it is time for the next step.
I am intrigued by the idea of using the script for administering my machine configurations.

My problem start with secret managing. It is not the first time I failed to implement sops-nix in my configuration.
I tried your repo, added a new host and with a new age-keypair I was ready to go.
As I understand, your scripts copies over the host-keys to generate the secrets.
I have the public ssh-host-key for my target system under the host/secret directory.  Also in the ssh-configuration of the script I inserted the path of the according secret ssh-host-key.

I always get 
```
sops-install-secrets: Imported /persist/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1g85r5cqldg9hrz3n6rmwz8e40x8wqrw5r6uxs54ecswpu4nzt3ls83ltfc
/nix/store/0igfrca140rvyiry2wxdvx2pqdw2rzdd-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt '/nix/store/dg5szfgaaqlq2knh7rc1sfcclwqpjja3-secrets.yaml': Error getting data key: 0 successful groups required, got 0
Activation script snippet 'setupSecretsForUsers' failed (1)
```
That goes for user and system secret creation.

It would be much appreciated if you could help me solving this problem. What am I misunderstanding? By the way your notes already helped a lot in understanding the usage of NixOS.

Best regards

lgo

**Comment by tiredofit** [comment]
No worries. I have moved into the correct repo.

Some thoughts:
- There are no quotes for the secrets - an example for common would be:

`common: Common Secret example`

and for users/secrets.yaml 

```
user-password: (password hash from mkpasswd)
root-password: (password hash from mkpasswd)
```

Just for experimentation are you able to create another key for your "host" - say under root? Towards the end of building the script I started getting desperate and using `sudo` and we may be running into some of those problems, where alot of it was related as well to secrets. So, adding a `&host_` of your local system, making sure it has a pub/private age key, and adding it to your hosts (or updating the deploy script to env vars in the top of the script to make sure the host and user is always added). This makes some sense if you could previously open the secrets, and then after a sops rekey with the new public keys it locks the original keys out. 

Otherwise there are some work arounds to allow a working installation and then try to figure out what is happening on a booted system by changing the root and the user you have created to have a hashedPassword and not rely on sops for the users for the first couple of generations. 

In the new year I'll have to build a "reset" environment for the deploy script and have it auto generate the keys it needed as opposed to relying on something already in place as I can see how this can be confusing. 

Keep me posted on the above..

**Comment by tom-tubeless** [comment]
Hey, back from the dungeon.

Thanks to your suggestions I progressed faster.

After running your script (and accepting the error), I ssh-ed into the target machine and mounted all created btrfs-volumes.
I chrooted into the `/mnt`-environment with `nixos-enter` and copied the `nixos-config`-direcotry over to the target.
I added the age key from the newly created `/persist/etc/ssh/ssh_host_ed25519_key.pub` to `.sops.yaml` and recreated the secrets (`users/secrets.yaml` , `hosts/../secrets/secrets.yaml`).
Then I finished with a bold `nixos-rebuild boot --flake .#flores ----option sandbox false`.

Now my machine is working with the sops-configuration.

Thank you very much (heading over to your home-config :) ).

**Comment by tiredofit** [comment]
Excellent! Glad you have made it past this hurdle. I have a couple interns starting in the next few weeks who I will have start fresh as you have and see if they encounter similar things and I will try to refine this to be easier for others. Enjoy!

**Comment by tom-tubeless** [comment]
That is great news. I will follow the changes in your repo and hope to learn a lot of it.
I hope you and your interns will share a good time.
